-- V0.14: evidence references existing experiment/candidate records; no duplicate trial engine.
CREATE TABLE causal_variables(id TEXT PRIMARY KEY, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE causal_hypotheses(id TEXT PRIMARY KEY, canonical_hash TEXT NOT NULL UNIQUE, status TEXT NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TRIGGER causal_hypotheses_no_delete BEFORE DELETE ON causal_hypotheses BEGIN SELECT RAISE(ABORT, 'causal hypothesis history is preserved'); END;
CREATE TRIGGER causal_hypotheses_identity BEFORE UPDATE ON causal_hypotheses WHEN OLD.id!=NEW.id OR OLD.canonical_hash!=NEW.canonical_hash OR json_remove(OLD.data,'$.status','$.evidence','$.updated_at')!=json_remove(NEW.data,'$.status','$.evidence','$.updated_at') BEGIN SELECT RAISE(ABORT, 'causal claim semantics are immutable; propose a scoped revision'); END;
CREATE TABLE causal_hypothesis_revisions(hypothesis_id TEXT NOT NULL REFERENCES causal_hypotheses(id), revision INTEGER NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)), PRIMARY KEY(hypothesis_id, revision));
CREATE TABLE causal_conditions(hypothesis_id TEXT NOT NULL REFERENCES causal_hypotheses(id), position INTEGER NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)), PRIMARY KEY(hypothesis_id,position));
CREATE TABLE causal_investigations(id TEXT PRIMARY KEY, model_id TEXT NOT NULL UNIQUE, data TEXT NOT NULL CHECK(json_valid(data)), spec TEXT NOT NULL CHECK(json_valid(spec)));
CREATE INDEX causal_investigation_target ON causal_investigations(json_extract(data,'$.target.kind'),json_extract(data,'$.target.target'));
CREATE TRIGGER causal_investigations_identity BEFORE UPDATE ON causal_investigations WHEN OLD.id!=NEW.id OR OLD.model_id!=NEW.model_id OR OLD.spec!=NEW.spec BEGIN SELECT RAISE(ABORT, 'registered causal fixture adapter is immutable'); END;
CREATE TRIGGER causal_investigations_no_delete BEFORE DELETE ON causal_investigations BEGIN SELECT RAISE(ABORT, 'causal investigation history is preserved'); END;
CREATE TABLE interventions(id TEXT PRIMARY KEY, investigation_id TEXT NOT NULL REFERENCES causal_investigations(id), request_id TEXT NOT NULL UNIQUE, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE counterfactual_pairs(id TEXT PRIMARY KEY, intervention_id TEXT NOT NULL UNIQUE REFERENCES interventions(id), experiment_id TEXT NOT NULL UNIQUE REFERENCES experiment_requests(id), data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE causal_evidence(id TEXT PRIMARY KEY, hypothesis_id TEXT NOT NULL REFERENCES causal_hypotheses(id), pair_id TEXT NOT NULL REFERENCES counterfactual_pairs(id), data TEXT NOT NULL CHECK(json_valid(data)), UNIQUE(hypothesis_id,pair_id));
CREATE INDEX causal_evidence_hypothesis ON causal_evidence(hypothesis_id);
CREATE TABLE causal_models(id TEXT NOT NULL, revision INTEGER NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)), PRIMARY KEY(id,revision));
CREATE TABLE causal_model_edges(model_id TEXT NOT NULL, revision INTEGER NOT NULL, hypothesis_id TEXT NOT NULL REFERENCES causal_hypotheses(id), data TEXT NOT NULL CHECK(json_valid(data)), FOREIGN KEY(model_id,revision) REFERENCES causal_models(id,revision), PRIMARY KEY(model_id,revision,hypothesis_id));
CREATE TABLE causal_gaps(model_id TEXT NOT NULL, revision INTEGER NOT NULL, position INTEGER NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)), FOREIGN KEY(model_id,revision) REFERENCES causal_models(id,revision), PRIMARY KEY(model_id,revision,position));
CREATE TABLE causal_artifact_dependencies(hypothesis_id TEXT NOT NULL REFERENCES causal_hypotheses(id), artifact_id TEXT NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)), PRIMARY KEY(hypothesis_id,artifact_id));
CREATE INDEX causal_dependencies_artifact ON causal_artifact_dependencies(artifact_id);
CREATE TABLE causal_revalidations(sequence INTEGER PRIMARY KEY AUTOINCREMENT, hypothesis_id TEXT NOT NULL REFERENCES causal_hypotheses(id), artifact_id TEXT NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE INDEX causal_revalidation_artifact ON causal_revalidations(artifact_id);
CREATE TABLE causal_refinements(investigation_id TEXT NOT NULL REFERENCES causal_investigations(id), hypothesis_id TEXT NOT NULL REFERENCES causal_hypotheses(id), data TEXT NOT NULL CHECK(json_valid(data)), PRIMARY KEY(investigation_id,hypothesis_id));
CREATE TABLE causal_remote_claims(sequence INTEGER PRIMARY KEY AUTOINCREMENT, hypothesis_id TEXT NOT NULL REFERENCES causal_hypotheses(id), data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE causal_events(sequence INTEGER PRIMARY KEY AUTOINCREMENT, subject TEXT NOT NULL, kind TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE causal_observations(investigation_id TEXT NOT NULL REFERENCES causal_investigations(id), experience_id TEXT NOT NULL REFERENCES experiences(id), data TEXT NOT NULL CHECK(json_valid(data)), PRIMARY KEY(investigation_id,experience_id));
CREATE TRIGGER causal_observations_no_update BEFORE UPDATE ON causal_observations BEGIN SELECT RAISE(ABORT, 'causal observations are immutable'); END;
CREATE TRIGGER causal_observations_no_delete BEFORE DELETE ON causal_observations BEGIN SELECT RAISE(ABORT, 'causal observations are immutable'); END;
CREATE TRIGGER causal_variables_no_update BEFORE UPDATE ON causal_variables BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_variables_no_delete BEFORE DELETE ON causal_variables BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_hypothesis_revisions_no_update BEFORE UPDATE ON causal_hypothesis_revisions BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_hypothesis_revisions_no_delete BEFORE DELETE ON causal_hypothesis_revisions BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_conditions_no_update BEFORE UPDATE ON causal_conditions BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_conditions_no_delete BEFORE DELETE ON causal_conditions BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER interventions_no_update BEFORE UPDATE ON interventions BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER interventions_no_delete BEFORE DELETE ON interventions BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER counterfactual_pairs_no_update BEFORE UPDATE ON counterfactual_pairs BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER counterfactual_pairs_no_delete BEFORE DELETE ON counterfactual_pairs BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_evidence_no_update BEFORE UPDATE ON causal_evidence BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_evidence_no_delete BEFORE DELETE ON causal_evidence BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_models_no_update BEFORE UPDATE ON causal_models BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_models_no_delete BEFORE DELETE ON causal_models BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_model_edges_no_update BEFORE UPDATE ON causal_model_edges BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_model_edges_no_delete BEFORE DELETE ON causal_model_edges BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_gaps_no_update BEFORE UPDATE ON causal_gaps BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_gaps_no_delete BEFORE DELETE ON causal_gaps BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_artifact_dependencies_no_update BEFORE UPDATE ON causal_artifact_dependencies BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_artifact_dependencies_no_delete BEFORE DELETE ON causal_artifact_dependencies BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_revalidations_no_update BEFORE UPDATE ON causal_revalidations BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_revalidations_no_delete BEFORE DELETE ON causal_revalidations BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_refinements_no_update BEFORE UPDATE ON causal_refinements BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_refinements_no_delete BEFORE DELETE ON causal_refinements BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_remote_claims_no_update BEFORE UPDATE ON causal_remote_claims BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_remote_claims_no_delete BEFORE DELETE ON causal_remote_claims BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_events_no_update BEFORE UPDATE ON causal_events BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
CREATE TRIGGER causal_events_no_delete BEFORE DELETE ON causal_events BEGIN SELECT RAISE(ABORT, 'causal provenance is append-only'); END;
