CREATE TABLE hardknock_nodes (id TEXT PRIMARY KEY,key_revision INTEGER NOT NULL CHECK(key_revision > 0),created_at TEXT NOT NULL,data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE node_key_revisions (node_id TEXT NOT NULL,revision INTEGER NOT NULL CHECK(revision > 0),valid_from TEXT NOT NULL,data TEXT NOT NULL CHECK(json_valid(data)),PRIMARY KEY(node_id,revision));
CREATE TABLE sync_peers (node_id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE,trust TEXT NOT NULL,status TEXT NOT NULL,data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE sync_cursors (peer_id TEXT NOT NULL,stream TEXT NOT NULL,position TEXT NOT NULL,updated_at TEXT NOT NULL,data TEXT NOT NULL CHECK(json_valid(data)),PRIMARY KEY(peer_id,stream));
CREATE TABLE sync_sessions (id TEXT PRIMARY KEY,peer_id TEXT NOT NULL,direction TEXT NOT NULL,status TEXT NOT NULL,started_at TEXT NOT NULL,completed_at TEXT,data TEXT NOT NULL CHECK(json_valid(data)));
CREATE INDEX sync_session_history ON sync_sessions(started_at DESC,id);
CREATE TABLE sync_envelopes (id TEXT PRIMARY KEY,sender TEXT NOT NULL,nonce TEXT NOT NULL,created_at TEXT NOT NULL,received_at TEXT NOT NULL,data TEXT NOT NULL CHECK(json_valid(data)),UNIQUE(sender,nonce));
CREATE TABLE sync_artifacts (id TEXT PRIMARY KEY,origin_node TEXT NOT NULL,origin_artifact TEXT NOT NULL,revision INTEGER NOT NULL,root_node TEXT NOT NULL,root_artifact TEXT NOT NULL,root_revision INTEGER NOT NULL,content_hash TEXT NOT NULL,artifact_type TEXT NOT NULL,created_at TEXT NOT NULL,data TEXT NOT NULL CHECK(json_valid(data)),UNIQUE(root_node,root_artifact,root_revision,content_hash));
CREATE INDEX sync_artifact_origin ON sync_artifacts(origin_node,origin_artifact,revision);
CREATE INDEX sync_artifact_root ON sync_artifacts(root_node,root_artifact,root_revision);
CREATE TABLE sync_artifact_receipts (artifact_id TEXT NOT NULL REFERENCES sync_artifacts(id),envelope_id TEXT NOT NULL REFERENCES sync_envelopes(id),received_from TEXT NOT NULL,received_at TEXT NOT NULL,relay_path TEXT NOT NULL CHECK(json_valid(relay_path)),PRIMARY KEY(artifact_id,envelope_id));
CREATE TABLE remote_knowledge_records (artifact_id TEXT PRIMARY KEY REFERENCES sync_artifacts(id),local_state TEXT NOT NULL,received_at TEXT NOT NULL,updated_at TEXT NOT NULL,data TEXT NOT NULL CHECK(json_valid(data)));
CREATE INDEX remote_knowledge_state ON remote_knowledge_records(local_state,updated_at DESC);
CREATE TABLE remote_contradictions (id TEXT PRIMARY KEY,target_hash TEXT NOT NULL,received_at TEXT NOT NULL,data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE environment_manifests (id TEXT PRIMARY KEY,node_id TEXT NOT NULL,captured_at TEXT NOT NULL,data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE artifact_revocations (id TEXT PRIMARY KEY,origin_node TEXT NOT NULL,artifact_hash TEXT NOT NULL,created_at TEXT NOT NULL,data TEXT NOT NULL CHECK(json_valid(data)),UNIQUE(origin_node,artifact_hash));
CREATE TABLE reproduction_queue (id TEXT PRIMARY KEY,artifact_hash TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,data TEXT NOT NULL CHECK(json_valid(data)),UNIQUE(artifact_hash));
CREATE TABLE sync_events (sequence INTEGER PRIMARY KEY AUTOINCREMENT,event TEXT NOT NULL,subject TEXT,created_at TEXT NOT NULL,data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TRIGGER node_key_revision_no_update BEFORE UPDATE ON node_key_revisions BEGIN SELECT RAISE(ABORT,'Node key revisions are immutable'); END;
CREATE TRIGGER node_key_revision_no_delete BEFORE DELETE ON node_key_revisions BEGIN SELECT RAISE(ABORT,'Node key revisions are retained'); END;
CREATE TRIGGER sync_envelope_no_update BEFORE UPDATE ON sync_envelopes BEGIN SELECT RAISE(ABORT,'Sync envelopes are immutable'); END;
CREATE TRIGGER sync_envelope_no_delete BEFORE DELETE ON sync_envelopes BEGIN SELECT RAISE(ABORT,'Sync envelopes are retained'); END;
CREATE TRIGGER sync_artifact_no_update BEFORE UPDATE ON sync_artifacts BEGIN SELECT RAISE(ABORT,'Sync artifacts are immutable'); END;
CREATE TRIGGER sync_artifact_no_delete BEFORE DELETE ON sync_artifacts BEGIN SELECT RAISE(ABORT,'Sync artifacts are retained'); END;
CREATE TRIGGER artifact_revocation_no_update BEFORE UPDATE ON artifact_revocations BEGIN SELECT RAISE(ABORT,'Artifact revocations are immutable'); END;
CREATE TRIGGER artifact_revocation_no_delete BEFORE DELETE ON artifact_revocations BEGIN SELECT RAISE(ABORT,'Artifact revocations are retained'); END;
CREATE TRIGGER sync_event_no_update BEFORE UPDATE ON sync_events BEGIN SELECT RAISE(ABORT,'Sync events are append only'); END;
CREATE TRIGGER sync_event_no_delete BEFORE DELETE ON sync_events BEGIN SELECT RAISE(ABORT,'Sync events are append only'); END;
